version: 2
updates:
  # NPM / Yarn dependencies
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
      types:
        patterns:
          - '@types/*'
      dev-dependencies:
        dependency-type: development

  # Dockerfile base images
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: ci
