import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { AuthService } from '../auth/auth.service';
import { UsersService } from '../users/users.service';

/** Defaults used to auto-create an admin when no explicit credentials are set. */
const DEFAULT_SEED_EMAIL = 'admin@flux.local';
const DEFAULT_SEED_USERNAME = 'admin';

/**
 * Seeds an initial admin on startup. Two modes:
 * - Explicit: when SEED_EMAIL and SEED_USERNAME are both provided, that user is
 *   created/promoted to admin (idempotent).
 * - Zero-config: otherwise, using SEED_PASSWORD (auto-generated by the runtime
 *   bootstrap) and default email/username, but only on a fresh install (empty
 *   users table) so an existing, operator-managed deployment is never touched.
 *
 * Runs after migrations (the docker entrypoint runs `migrate deploy` first).
 */
@Injectable()
export class SeedService implements OnApplicationBootstrap {
  private readonly logger = new Logger(SeedService.name);

  constructor(
    private readonly config: ConfigService,
    private readonly users: UsersService,
    private readonly auth: AuthService,
  ) {}

  async onApplicationBootstrap(): Promise<void> {
    const password = this.config.get<string>('SEED_PASSWORD');
    if (!password) {
      return;
    }

    const explicit =
      !!this.config.get<string>('SEED_EMAIL') &&
      !!this.config.get<string>('SEED_USERNAME');
    const email = this.config.get<string>('SEED_EMAIL') ?? DEFAULT_SEED_EMAIL;
    const username =
      this.config.get<string>('SEED_USERNAME') ?? DEFAULT_SEED_USERNAME;

    try {
      // Without explicit credentials, only seed a brand-new install so we never
      // inject an admin into a deployment that already manages its own users.
      if (!explicit && (await this.users.count()) > 0) {
        return;
      }
      const existing = await this.users.findByEmailOrUsername(email, username);
      if (existing) {
        if (existing.role !== 'admin') {
          await this.users.setRole(existing.id, 'admin');
          this.logger.log(`Promoted seed user "${username}" to admin`);
        } else {
          this.logger.log(`Seed user "${username}" already exists, skipping`);
        }
        return;
      }
      const created = await this.auth.register({ email, username, password });
      await this.users.setRole(created.id, 'admin');
      this.logger.log(`Seeded initial admin user "${username}"`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'unknown error';
      this.logger.error(`Failed to seed user: ${message}`);
    }
  }
}
